name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Django Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./
        
      

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: my_recipe_database
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: supersecure
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1
      DEBUG: True
      POSTGRES_DB: my_recipe_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecure
      DB_HOST: localhost
      DB_PORT: 5432
      

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
    
        run: |
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py test

      # - name: Run Django tests
      #   run: |
      #     python manage.py migrate
      #     python manage.py test

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build frontend
        run: npm run build
